# Generated by Django 4.2 on 2023-04-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_type',
            field=models.CharField(choices=[('action', 'action'), ('blockbuster', 'blockbuster'), ('horror', 'horror'), ('comedian', 'comedian'), ('thriller', 'thriller'), ('romance', 'romance')], default='action', max_length=200),
        ),
    ]
